#!/usr/bin/env zsh

if [[ -z $1 ]]; then
  echo "Error: missing argument for binary to lint"
  echo "USAGE: $0 BINARY"
  exit 1
fi

imposter="$1"

file1=/tmp/cat_linter_file1
file2=/tmp/cat_linter_file2
file1_content="test\nsomething\nhere"
file2_content="other\nthings\nhere"
echo "$file1_content" > $file1
echo "$file2_content" > $file2

function compare_output {
  if [[ $1 == $2 ]]; then
    echo "  Output matches"
  else
    echo "  ERROR: Output didn't match\n    Expected: '$1'\n         Got: '$2'"
    exit 1
  fi
}

function compare_exit {
  if [[ $1 -eq $2 ]]; then
    echo "  Exit matches"
  else
    echo "  Expected: '$1'\n         Got: '$2'"
    exit 1
  fi
}

echo "Linting cat against $imposter"

# The command:
#
#       cat file1
#
# will print the contents of file1 to the standard output.

echo "\nChecking \`cat $file1\`":

cat_output=$(cat $file1)
cat_exit=$?
imposter_output=$($imposter $file1)
imposter_exit=$?

compare_output $cat_output $imposter_output
compare_exit $cat_exit $imposter_exit

echo "\nChecking \`echo \"hi\\\nnow\" | cat\`"

cat_output=$(echo "hi\nnow" | cat)
cat_exit=$?
imposter_output=$(echo "hi\nnow" | $imposter)
imposter_exit=$?

compare_output $cat_output $imposter_output
compare_exit $cat_exit $imposter_exit

echo "\nChecking \`cat $file1 $file2\`"

cat_output=$(cat $file1 $file2)
cat_exit=$?
imposter_output=$($imposter $file1 $file2)
imposter_exit=$?

compare_output $cat_output $imposter_output
compare_exit $cat_exit $imposter_exit

echo "\nChecking \`cat $file1 non-existent-file \`"

cat_output=$(cat $file1 /tmp/non-existent-file 2>&1)
cat_exit=$?
imposter_output=$($imposter $file1 /tmp/non-existent-file 2>&1)
imposter_exit=$?

compare_output $cat_output $imposter_output
compare_exit $cat_exit $imposter_exit

echo "\nChecking \`echo \"how\\\nnow\\\nbrown\\\ncow\" | cat $file1 - $file2\`"

cat_output=$(echo "how\nnow\nbrown\ncow" | cat $file1 - $file2 2>&1)
cat_exit=$?
imposter_output=$(echo "how\nnow\nbrown\ncow" | $imposter $file1 - $file2 2>&1)
imposter_exit=$?

compare_output $cat_output $imposter_output
compare_exit $cat_exit $imposter_exit
