#!/usr/bin/env zsh

if [[ -z $1 ]]; then
  echo "Error: missing argument for binary to lint"
  echo "USAGE: $0 BINARY"
  exit 1
fi

imposter="$1"

# Check we can call imposter
a=$(echo "" | $imposter)
if [[ ! $? -eq 0 ]]; then
	echo "ERROR: failed to call $imposter"
	exit 1
fi


file1=/tmp/cat_linter_file1
file2=/tmp/cat_linter_file2
file1_content="test\nsomething\nhere"
file2_content="other\nthings\nhere"
echo "$file1_content" > $file1
echo "$file2_content" > $file2

function compare_output {
  if [[ $1 == $2 ]]; then
    echo "  Output matches"
  else
    echo "  ERROR: Output didn't match"
    echo
    echo "  Expected: '$1'"
    echo "       Got: '$2'"
    echo
    exit 1
  fi
}

function compare_exit {
  if [[ $1 -eq $2 ]]; then
    echo "  Exit matches"
  else
    echo "ERROR: Exit code didn't match"
    echo
    echo "  Expected: '$1'"
    echo "       Got: '$2'"
    echo
    exit 1
  fi
}

echo "Linting cat against $imposter"

# The command:
#
#       cat file1
#
# will print the contents of file1 to the standard output.

echo "\nChecking \`cat $file1\`":

cat_output=$(cat $file1)
cat_exit=$?
imposter_output=$($imposter $file1)
imposter_exit=$?

compare_output $cat_output $imposter_output
compare_exit $cat_exit $imposter_exit

echo "\nChecking \`cat $file1 $file2\`"

cat_output=$(cat $file1 $file2)
cat_exit=$?
imposter_output=$($imposter $file1 $file2)
imposter_exit=$?

compare_output $cat_output $imposter_output
compare_exit $cat_exit $imposter_exit

echo "\nChecking \`cat $file1 non-existent-file \`"

cat_output=$(cat $file1 /tmp/non-existent-file 2>&1)
cat_exit=$?
imposter_output=$($imposter $file1 /tmp/non-existent-file 2>&1)
imposter_exit=$?

compare_output $cat_output $imposter_output
compare_exit $cat_exit $imposter_exit

echo "\nChecking \`echo \"hi\\\nnow\" | cat\`"

cat_output=$(echo "hi\nnow" | cat)
cat_exit=$?
imposter_output=$(echo "hi\nnow" | $imposter)
imposter_exit=$?

compare_output $cat_output $imposter_output
compare_exit $cat_exit $imposter_exit

echo "\nChecking \`echo \"how\\\nnow\\\nbrown\\\ncow\" | cat $file1 - $file2\`"

cat_output=$(echo "how\nnow\nbrown\ncow" | cat $file1 - $file2 2>&1)
cat_exit=$?
imposter_output=$(echo "how\nnow\nbrown\ncow" | $imposter $file1 - $file2 2>&1)
imposter_exit=$?

compare_output $cat_output $imposter_output
compare_exit $cat_exit $imposter_exit

echo "\nChecking \`echo \"how\\\nnow\\\nbrown\\\ncow\" | cat $file1 - /tmp/non-existent-file - $file2\`"

cat_output=$(echo "how\nnow\nbrown\ncow" | cat $file1 - /tmp/non-existent-file - $file2 2>&1)
cat_exit=$?
imposter_output=$(echo "how\nnow\nbrown\ncow" | $imposter $file1 - /tmp/non-existent-file - $file2 2>&1)
imposter_exit=$?

compare_output $cat_output $imposter_output
compare_exit $cat_exit $imposter_exit

if which socat > /dev/null 2> /dev/null; then
  function setup_socket() {
    socket="$1"
    rm -f "${socket}"
    (echo "Linting my cat" | socat STDIN "UNIX-LISTEN:${socket}") &
    while ! test -S "${socket}"
    do
      sleep 0.1
    done
  }

  echo "\nChecking UNIX socket reading capabilities"

  socket="/tmp/cat_linter.sock"
  setup_socket "${socket}"

  cat_output=$(cat ${socket} 2>&1)
  cat_exit=$?

  setup_socket "${socket}"
  imposter_output=$(${imposter} ${socket} 2>&1)
  imposter_exit=$?

  compare_output $cat_output $imposter_output
  compare_exit $cat_exit $imposter_exit
else
  echo "\nNot checking UNIX socket reading capabilities - install socat for that\n"
fi
